name: Build documentation
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: "doc/requirements_doc.txt

            "
          python-version: "3.12"
      - name: Install dependencies
        run: "python -m pip install --upgrade pip

          python -m pip install -r requirements.txt

          python -m pip install git+https://github.com/tensorly/tensorly-sphinx-theme.git@main

          python -m pip install -r doc/requirements_doc.txt

          "
      - id: measurement-4
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - name: Install package
        run: "python -m pip install -e .

          "
      - id: measurement-6
        name: Record Measurement After Install package
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install package
          task: get-measurement
      - name: Make doc
        run: "cd doc

          python minify.py

          make html

          cd ..

          "
        continue-on-error: true
      - id: measurement-8
        name: Record Measurement After Make doc
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Make doc
          task: get-measurement
