name: Build documentation
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: 'doc/requirements_doc.txt

            '
          python-version: '3.12'
      - name: Install dependencies
        run: 'python -m pip install --upgrade pip

          python -m pip install -r requirements.txt

          python -m pip install git+https://github.com/tensorly/tensorly-sphinx-theme.git@main

          python -m pip install -r doc/requirements_doc.txt

          '
      - id: measurement-4
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - name: Install package
        run: 'python -m pip install -e .

          '
      - id: measurement-6
        name: Record Measurement After Install package
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install package
          task: get-measurement
      - name: Make doc
        run: 'cd doc

          python minify.py

          make html

          cd ..

          '
      - id: measurement-8
        name: Record Measurement After Make doc
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Make doc
          task: get-measurement
      - if: success() && github.ref == 'refs/heads/main'
        name: Push doc to website
        run: '# Add deploy key and clone through ssh

          eval "$(ssh-agent -s)"

          mkdir ~/.ssh

          echo "${{ secrets.DEPLOY_DOC_KEY }}" > ~/.ssh/id_rsa

          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -t rsa github.com

          echo ''Documentation was successfully built, updating the website.''

          # See https://github.community/t/github-actions-bot-email-address/17204/5

          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git config --global user.name "github-actions"

          git clone "git@github.com:tensorly/tensorly.github.io.git" doc_folder

          echo "-- Updating the content"

          cd doc_folder

          git rm -r dev/*

          mkdir -p dev

          echo "Copying to folder"

          cp -r ../doc/_build/html/* dev/

          echo "Pushing to git"

          git add dev

          git commit -m "Github action: auto-update."

          git push --force origin main

          '
      - id: measurement-10
        name: Record Measurement After Push doc to website
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Push doc to website
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
