name: Test TensorLy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: 'requirements.txt

            '
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and backend ${{matrix.BACKEND}}
        run: "python -m pip install --upgrade pip\npython -m pip install -r requirements.txt\n\
          python -m pip install -r doc/requirements_doc.txt\necho \"Installing dependencies\
          \ for BACKEND=${{matrix.BACKEND}}\"\nif [[ \"${{matrix.BACKEND}}\" == \"\
          numpy\" ]]; then\n  echo \"Installing sparse\";\n  pip install sparse;\n\
          elif [[ \"${{matrix.BACKEND}}\" == \"pytorch\" ]]; then\n  echo \"Installing\
          \ PyTorch\";\n  pip install torch torchvision;\nelif [[ \"${{matrix.BACKEND}}\"\
          \ == \"tensorflow\" ]]; then\n  echo \"Installing TensorFlow\";\n  pip install\
          \ tensorflow;\nelif [[ \"${{matrix.BACKEND}}\" == \"jax\" ]]; then\n  echo\
          \ \"Installing JAX\";\n  pip install jax jaxlib;\nelif [[ \"${{matrix.BACKEND}}\"\
          \ == \"paddle\" ]]; then\n  echo \"Installing PaddlePaddle\";\n  pip install\
          \ 'setuptools>=65.0';\n  pip install paddlepaddle==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cpu/;\n\
          fi\n"
      - id: measurement-4
        name: Record Measurement After Install dependencies and backend ${{matrix.BACKEND}}
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install dependencies and backend ${{matrix.BACKEND}}
          task: get-measurement
      - name: Install package
        run: 'python -m pip install -e .

          '
      - id: measurement-6
        name: Record Measurement After Install package
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install package
          task: get-measurement
      - name: Test with backend ${{matrix.BACKEND}} pytest and coverage
        run: 'TENSORLY_BACKEND=${{matrix.BACKEND}} pytest -vv --cov tensorly --cov-report
          xml --durations=10 tensorly

          '
      - id: measurement-8
        name: Record Measurement After Test with backend ${{matrix.BACKEND}} pytest
          and coverage
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Test with backend ${{matrix.BACKEND}} pytest and coverage
          task: get-measurement
      - name: Check coverage with CodeCov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          verbose: true
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    strategy:
      fail-fast: false
      matrix:
        BACKEND:
          - numpy
          - pytorch
          - paddle
        include:
          - BACKEND: numpy
            python-version: '3.9'
          - BACKEND: numpy
            TENSORLY_TENALG_BACKEND:
              - einsum
            python-version: '3.11'
          - BACKEND: jax
            TENSORLY_TENALG_BACKEND:
              - einsum
            python-version: '3.13'
          - BACKEND: tensorflow
            TENSORLY_TENALG_BACKEND:
              - einsum
            python-version: '3.12'
        python-version:
          - '3.12'
